/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ButtonProps {
  text: string;
  className?: string;
  children?: React.ReactNode;
}

const Button: React.FC<ButtonProps> = ({ text, className, children }) => {
  return (
    <button className={className}>
      {text}
      {children}
    </button>
  );
};

export default Button;
