/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Button from "./Button";

const Header: React.FC = () => {
  return (
    <header className="flex flex-wrap gap-5 justify-between self-stretch text-white max-md:max-w-full">
      <h1 className="text-4xl font-bold">Bull Street</h1>
      <Button
        text="Connect Wallet"
        className="flex relative flex-col px-6 py-2 my-auto text-lg aspect-[4.611] w-[166px] max-md:pr-5"
      >
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/0582c7247d53738f133515ca814e211de52b18cff7975b74c63fb6cf941941ca?placeholderIfAbsent=true&apiKey=779eb5ea1637423490797e9103078d7f"
          alt=""
          className="object-cover absolute inset-0 size-full"
        />
      </Button>
    </header>
  );
};

export default Header;
